# Generated by Django 5.0.14 on 2025-08-27 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["sender", "status"], name="connections_sender__951803_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["receiver", "status"], name="connections_receive_44aadd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("sender", "receiver")},
        ),
    ]
